### ISSUE TITLE
Unread message counter is not updated

### ISSUE THREAD

**Issue by Muffo** [boukestam/inbox-in-gmail#35]
The unread message counter displayed in the sidebar on the left is not updated when I read messages.

![image](https://user-images.githubusercontent.com/538925/55904292-59af9280-5b84-11e9-90cd-49189e5f4bcb.png)

Note that the counter displayed in the browser tab (near the favicon) works OK.

**Comment by joeytroy** [comment]
@Muffo This has been fixed. We have just hid the numbers since they do not update
https://github.com/inbox-in-gmail/inbox-in-gmail/commit/e9e3c92d4f19be1f72dbaca4b925fed22ba6e537

**Comment by Muffo** [comment]
Great! No number is better than wrong number :)

**Comment by Muffo** [comment]
Has this already been released? I am on 0.4.6 and I still see the number.
